### ISSUE TITLE
RPI Zero PCB

### ISSUE THREAD

**Issue by aalzooke** [mikelawrence/RPi_Zero_pHat_Template#1]
Do you have a similar template to the RPI zero including all the components? I'm trying to build a similar board to the RPI Zero. Can you please help me? 
Thank you for your time.

**Comment by mikelawrence** [comment]
Assuming you mean design files for a RPI Zero, no I do not have any.

**Comment by aalzooke** [comment]
I'm planning to build a smart Bell, I have all the code, I need something similar to RPI Zero but I don't know where to start and I don't know how much it will cost to build my own. 
DO you have any suggestion to me? 
Thank you

**Comment by aalzooke** [comment]
I'm a software engineer, so i don't have experience in hardware.  Would you be able to create something similar to RPI zero and I will pay you for the work? 
Thank you

**Comment by mikelawrence** [comment]
Sorry I'm not interested.
